
pipeline {
    agent any

    stages {

    stage('Run Tests') {
            steps {
                sh 'cd webapp && npm test'
                // Run tests  
            }
        }

//     stage('Build') {
//             steps {
//                 sh 'ls'
//                 sh 'cd webapp && docker build -t weave:latest .'
//                 sh 'docker login -u myuser -p mypassword docker.io
// '
                
//             } 
//         } 
   /*  stage('deploy to remote server') {
            steps {
                
                 sh 'ansible-playbook -i build/inventory.ini build/dockerbuild-playbook.yml'
               
            }
           
        }  */

    stage('Deploy') {
            steps {
                // Deploy the application
               echo "Deploying"
                sh 'ansible-playbook -i build/inventory.ini build/dockerbuild-playbook.yml'

            }
        }
    }

}
